version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

